stages:
  - build_test
  - dockerize
  - deploy

build_test:
  stage: build_test
  interruptible: true
  image: hseeberger/scala-sbt:11.0.13_1.5.7_2.13.7
  script:
    - sbt assembly
  artifacts:
    name: "radioware-relay-server-$CI_COMMIT_SHORT_SHA.jar"
    paths:
      - target/scala-2.13/radioware-relay-server.jar

dockerize:
  stage: dockerize
  interruptible: true
  dependencies:
    - build_test
  script:
    - docker image build --tag radioware-relay:$CI_COMMIT_SHORT_SHA .
    - docker image tag radioware-relay:$CI_COMMIT_SHORT_SHA radioware-relay:latest

deploy:
  stage: deploy
  interruptible: true
  image: alpine/curl:3.14
  script:
    - curl http://127.0.0.1:7000/api/private/v1/deploy/radioware-relay
