stages:
  - build_test
  - dockerize
  - deploy

build_test:
  stage: build_test
  interruptible: true
  image: sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0
  script:
    - sbt assembly
  artifacts:
    name: "radioware-relay-server-$CI_COMMIT_SHORT_SHA.jar"
    paths:
      - target/scala-3.2.0/radioware-relay-server.jar

dockerize:
  stage: dockerize
  interruptible: true
  dependencies:
    - build_test
  script:
    - docker image build --tag radioware/relay:$CI_COMMIT_SHORT_SHA --tag radioware/relay:latest .

deploy:
  stage: deploy
  interruptible: true
  image: alpine/curl:3.14
  script:
    - curl http://172.17.0.1:7000/api/private/v1/deploy/radioware-relay
